Feat/reset offset
michelin/ns4kafka pull request #58
Opened 2021-06-02 11:56 UTC by Debatent

2021-06-03 09:30 UTC, Debatent commented
#61

2021-06-07 23:45 UTC, twobeeb requested changes

2021-06-07 23:45 UTC, twobeeb commented on api/src/test/java/com/michelin/ns4kafka/controllers/ConsumerGroupControllerTest.java
> +        assertEquals(result.getStatus().getOffsetChanged().get(topicPartition1.toString()), 5L);
Expected goes first

2021-06-07 23:45 UTC, twobeeb commented on api/src/test/java/com/michelin/ns4kafka/controllers/ConsumerGroupControllerTest.java
> +        assertThrows(ResourceValidationException.class,
Validate the ResourceValidationException message

2021-06-07 23:45 UTC, twobeeb commented on api/src/test/java/com/michelin/ns4kafka/controllers/ConsumerGroupControllerTest.java
> +                () -> consumerGroupController.resetOffsets("test", "groupID", resetOffset, false));
Validate the ResourceValidationException message

2021-06-07 23:45 UTC, twobeeb commented on api/src/test/java/com/michelin/ns4kafka/controllers/ConsumerGroupControllerTest.java
> +                () -> consumerGroupController.resetOffsets("test", "groupID", resetOffset, false));
Validate the ResourceValidationException message

2021-06-07 23:45 UTC, twobeeb commented on api/src/test/java/com/michelin/ns4kafka/services/ConsumerGroupServiceTest.java
> +        assertTrue(result.size() == 1);
use assertEquals

2021-06-07 23:45 UTC, twobeeb commented on api/src/test/java/com/michelin/ns4kafka/services/ConsumerGroupServiceTest.java
> +        assertTrue(result.size() == 1);
use assertEquals

2021-06-07 23:45 UTC, twobeeb commented on api/src/test/java/com/michelin/ns4kafka/services/ConsumerGroupServiceTest.java
> +        }
don't do this

2021-06-07 23:45 UTC, twobeeb commented on api/src/test/java/com/michelin/ns4kafka/services/ConsumerGroupServiceTest.java
> +        }
don't do this, call normally

2021-06-07 23:45 UTC, twobeeb commented on cli/src/main/java/com/michelin/ns4kafka/cli/services/ConsumerGroupService.java
> +}
Integrate this in ResourceService

2021-06-07 23:45 UTC, twobeeb commented on cli/src/main/java/com/michelin/ns4kafka/cli/client/ConsumerGroupClient.java
> +}
Integrate this in NamespacedResourceClient

2021-06-09 16:58 UTC, merged